version: '3.8'

services:
  Swayam-Bazaar-Application:
    container_name: swayam-bazaar-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    
